server:
  port: 8084

#  spring config server
spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8008"

#spring cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # (1)
      routes:
#-------------------route custom -----------------------
        - id: user-service-openapi
          uri:  lb://USER-SERVICE    #euraka service name
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}


        - id: task-service-openapi
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**
          filters:
            - RewritePath=/tasks/(?<path>.*), /$\{path}
#-------------------route custom -----------------------



#------------------ original route-------------
        - id: user-service
          uri:  lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**,/api/v1/groups/**
#          filters: #notice
#            - RewritePath=/api/v1/users/(?<path>.*), /$\{path}

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/v1/tasks/**
#          filters:  #notice
#            - RewritePath=/api/v1/tasks/(?<path>.*), /$\{path}
#------------------ original route-------------


#------------------allow swagger ---------------------
        # (2)
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      # (3)
      - name: users
        url: /v3/api-docs/users
      - name: tasks
        url: /v3/api-docs/tasks



